### ISSUE TITLE
Dumping empty ValuesClause

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#1]
SELECT ?v WHERE {?v <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/TR/2003/CR-owl-guide-20030818/wine#VintageYear> .}

**Comment by Jeroen537** [comment]
Deze query parsed niet meer bij mij. Ook niet op de testsite http://www.sparql.org/query.html.
Iets misgegaan met copy/paste?

**Comment by Jeroen537** [comment]
Zelfde probleem. Omring de http://'s met <> en het gaat wel.
Dat er aan het eind een lege ValuesClause in zit, klopt met de EBNF:
Query     ::=   Prologue ( SelectQuery | ConstructQuery | DescribeQuery | AskQuery) ValuesClause
De ValueClause is niet Optional in deze productie (geen "ValuesClause?"). Hij mag wel leeg zijn, en dat is hier het geval.
