### ISSUE TITLE
Incorrect error criterion "not a valid string for PNAME_NS element"

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#10]
Replacing a [PNAME_NS] element with a name consisting of underscores and numbers, e.g., '\_ns1', raises a _not a valid string for PNAME\_NS element_. According to the definition on `NCNAME` in [Namespaces in XML 1.1](https://www.w3.org/TR/2004/REC-xml-names11-20040204/#sec-namespaces), this character sequence is allowed, though.

**Code:**

```

from parsertools.parsers.sparqlparser import parseQuery, parser

q = '''
PREFIX ns:     <http://ds.tno.nl/ontoA/>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema>

SELECT ?p ?t WHERE 
    {
        ?p a foaf:Person .
        ?p ns:hasTemp ?t .
        ?p ns:hasAge ?a .
         ?t a ns:TempInC .
         FILTER ( (datatype(?t) = xsd:float) &&
                     ( ?t > 37.0 ) &&
                     ( ?a < 37.0 ) 
                 ).
    } 
'''

r = parseQuery(q)
print(r.dump())

prefixDecls = r.searchElements(element_type=parser.PrefixDecl)
for p in prefixDecls:
    ns, ln = str(p.namespace)[:-1], str(p.localname)
    print("namespace: {} = {}".format(ns, ln))

new_ns = '_ns1'
for p in prefixDecls:
    if str(p.namespace)[0:-1] == 'ns':
        print('updating {} with {}'.format(str(p.namespace),new_ns))
        p.namespace.updateWith(new_ns)

print('updated namespace:')
for p in prefixDecls:
    ns, ln = str(p.namespace)[:-1], str(p.localname)
    print("namespace: {} = {}".format(ns, ln))
```

**Output of this code:**  
(except for the Dump)
 
```
namespace: ns = <http://ds.tno.nl/ontoA/>
namespace: foaf = <http://xmlns.com/foaf/0.1/>
namespace: xsd = <http://www.w3.org/2001/XMLSchema>
Traceback (most recent call last):
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\base.py", line 152, in updateWith
    other = self.pattern.parseString(new_content)[0]
  File "C:\Users\brandtp\AppData\Local\Programs\Python\Python35\lib\site-packages\pyparsing-2.0.7-py3.5.egg\pyparsing.py", line 1129, in parseString
    raise exc
  File "C:\Users\brandtp\AppData\Local\Programs\Python\Python35\lib\site-packages\pyparsing-2.0.7-py3.5.egg\pyparsing.py", line 1119, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\Users\brandtp\AppData\Local\Programs\Python\Python35\lib\site-packages\pyparsing-2.0.7-py3.5.egg\pyparsing.py", line 997, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\brandtp\AppData\Local\Programs\Python\Python35\lib\site-packages\pyparsing-2.0.7-py3.5.egg\pyparsing.py", line 1876, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected PNAME_NS (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Workspaces\ParserScrapbook\src\root\nested\sparlparserKlad.py", line 35, in <module>
    p.namespace.updateWith(new_ns)
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\base.py", line 154, in updateWith
    raise ParsertoolsException('{} is not a valid string for {} element'.format(new_content, self.__class__.__name__))        
parsertools.ParsertoolsException: _ns1 is not a valid string for PNAME_NS element
updating ns: with _ns1

```

**Comment by plbt5** [comment]
Whoopsadaisy

I forgot to close the new ns name with a colon ':'.  
Closing the issue - was not an issue.

**Comment by Jeroen537** [comment]
Check.

Dank voor de nette input en output. Ik was er al naar aan het kijken, maar liep tegen andere output aan dan jij stuurde.

Wil je me het genoegen doen met de laatste versie te werken als ik die heb aangemeld? Zoals ik schreef heb ik nieuwe labels aangemaakt. Ik kan jouw output niet reproduceren omdat hij stuk loopt op een niet bestaand label.

A propos de opmerking “According to the definition on NCNAME in Namespaces in XML 1.1 <https://www.w3.org/TR/2004/REC-xml-names11-20040204/#sec-namespaces>, this character sequence is allowed, though” het volgende:  de XML regel is wel een aanwijzing, maar is niet allesbepalend. SPARQL namespace conventies zijn nl. niet altijd identiek aan XML namespace conventies. Zie hiervoor 4.1.1.1 in de SPARQL Query Language spec:
 “Note that SPARQL local names <https://www.w3.org/TR/sparql11-query/#rPN_LOCAL> allow leading digits while XML local names <http://www.w3.org/TR/2006/REC-xml-names11-20060816/#NT-LocalPart> do not. SPARQL local names <https://www.w3.org/TR/sparql11-query/#rPN_LOCAL> also allow the non-alphanumeric characters allowed in IRIs via backslash character escapes (e.g. ns:id\=123). SPARQL local names <https://www.w3.org/TR/sparql11-query/#rPN_LOCAL> have more syntactic restrictions than CURIE <http://www.w3.org/TR/curie/>s.”

Dus voorzichtigheid is geboden met het trekken van conclusies over SPARQL op basis van XML en vice versa.
 

Jeroen.

**Comment by plbt5** [comment]
Ja, ik zal trachten bij het indienen van een issue dat te doen obv de laatste build. Ik had jouw mail niet gezien, omdat ik thuis niet altijd de tunnel open en derhalve de mail niet ontvang. Hoe kan ik het build nummer uit de code halen? Dan kan ik dat vermelden in de issue.
