### ISSUE TITLE
Feature request: prefixIris() as opposite to expandIris()

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#14]
De methode expandIris() maakt vergelijken zonder namespace-gedoe een hoop eenvoudiger en consistenter. Maar het resultaat wordt wel een stuk lastiger te lezen voor de mens achter de tool. Vandaar dit feature request.

Dit is daarmee dus een schoonheids-feature (nice-to-have) en geen functionele feature (noodzakelijk); prio dus laag. 

Suggestie voor de uitvoering: 

1. De methode een namespace-tabel meegeven: 
```
query = parseQuery(querystring)
query.expandIris()
nsTable = { 
    pf1 : "<mijn/volledige/iri/1.0/specificatie#>",
    pf2 : "<mijn/volledige/iri/1.1/specificatie#>", 
    myPf3 : "<mijn/compleet/andere/volledige/iri/1.0/specificatie#>" 
}
query.prefixIris(ns-table=nsTable)
```
2. de methode de meest voor de hand liggende prefixes automatisch toevoegen: rdf, owl, rdfs, xml, ...

Alvast dank!
gr
     Paul

**Comment by Jeroen537** [comment]
ExpandiIris() is natuurlijk bedoeld voor de computer, en niet voor de mens. Het lijkt me dat je probleem is dat expandIris() de ParseStruct zelf verandert, zodat je de nette prefixes voor altijd kwijt bent en dus niet meer kunt teruglezen.

Als dat zo is, dan is de remedie eenvoudig. Wanneer je de expansie nodig hebt om te vergelijken, maar je wilt de prefixes toch ook zichtbaar houden, maak dan eerst een kopie (pseudocode):

A’ = A.copy()
A’.expandIris()
[doe vergelijking met A’]
[A is onaangetast en kan worden teruggelezen Alle pointers naar delen van A blijven werken.]

Je voorgestelde wijziging wil ik niet doorvoeren:

1. het gaat tegen de geest van SPARQL in, dat prefixes als shorthand ziet en wel uitlegt hoe die geëxpandeerd worden maar niet andersom
2. het is ingewikkeld, omdat je zaken moet gaan testen als: is de prefix al gedeclareerd? Zo nee, moet ik dan een prefix declaratie toevoegen, en waar dan wel? Zo ja, is de string die ik naar de prefix wil omzetten identiek aan de string die in de geldende prefix declaratie aan de prefix wordt toegekend? Zijn er nog andere zaken waar ik niet aan heb gedacht? Dit alles komt mede voort uit punt 1.
3. Het voorstel van boven voldoet denk ik.

Ik sluit de issue. Als dit niet werkt hoor ik het wel.

**Comment by plbt5** [comment]
Je voorgestelde oplossing werkt als ik alléén zou vergelijken. Maar daarenboven doe ik ook de vertaling, waardoor een oplossing gebaseerd op kopie niet meer werkt.

Echter, gezien jouw punt 1. en alle daarmee samenhangende problemen, zijn van dermate aard dat mijn voorgestelde wijziging meer kwaad dan goed doet. Akkoord.

Closed

**Comment by Jeroen537** [comment]
Ik wil hier wel over nadenken, misschien is er een andere weg. Heb je een eenvoudig voorbeeldprogramma voor me?
