### ISSUE TITLE
Discussion on Feature request: extend method getAncestors() to skip intermediate nodes

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#15]
Ik merk dat ik de getAncestors()-methode nooit gebruik om nodes te vinden die tussen de huidige en de eerste branching node ligt. Als gevolg daarvan gebruik ik `getAncestors()` altijd in combinatie met `isBranch()`, als volgt:
```
assert isinstance(node, ParseStruct)
for ancestor in node.getAncestors():
    if not ancestor.isBranch():
        # This ancestor is not a branching node. Skip to the next ancestor but remember 
        # this node, since, eventually, this will be the top node of this graph path before branching
        topOfBranch = ancestor
        continue
    elif type(ancestor).__name__ == 'ObjectListPath':
        ...
        break
    elif type(ancestor).__name__ == 'VarOrTerm':
        ...
        break
```

Daarmee heb ik dus altijd een for-loop die ik moet breken wanneer ik de branching-node gevonden heb die ik hebben wil.

Om dit te doorbreken zou een parameter `skip_intermediates = True` op getAncestors() de for-loop overbodig maken. 

Nadeel: Dat geeft tegelijkertijd wel een complicatie, want ik wil vaak weten uit welke branch deze ancestor gevonden is, omdat dat vaak de branch is die ik NIET wil inspecteren. Die houd ik nu vast met de lagging `topOfBranch`. Ik zie dan weer niet in hoe dat opgelost zou kunnen worden, zonder e.e.a. gecompliceerder te maken. Want op zich is deze code wel kristalhelder.

Hoe zie jij dit?

gr
    Paul

**Comment by Jeroen537** [comment]
Als je echt een variant van getAncestors() wilt die intermediates skipt, dan kun je zelf een convenience functie schrijven zoals (niet-getest):

def getBranchingAncestors(node):
	ancestors = node.getAncestors()
	return [a for a in ancestors if a.isBranch()]

Maar zoals je zelf al aangeeft heb je daar op zichzelf weinig aan.

Een elegantere variant van jouw code zou lopen via een herhaalde getParent(), totdat je bent waar je zijn wilt. Dan heb je zowel de branchende node als de kop van de juiste tak te pakken.  getAncestors() is in zekere zin overkill omdat je alleen maar tot de eerste branch gaat, de rest van de ancestors heb je niet nodig, en je moet ook een kunstgreep uithalen om de kop vast te houden.

Ook dit kun je eenvoudig in een convenience functie opnemen, die je naar behoefte kunt includen en aanroepen.

**Comment by plbt5** [comment]
Helder en akkoord.
Herhaalde `getParent()` is de koninklijke weg.
Dank.
