### ISSUE TITLE
[COMMA] absent in parsed query (version 0.2.6, build 2647)

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#16]
Bij het gebruik van comma's als kortschrift in een SPARQL query, wordt de ParseStruct-node van dat type niet weergegeven. De semicolon, die eenzelfde kortschriftfunctie heeft, wordt wel geparsed tot ParseStruct-node.

Beschouw de volgende voorbeeld-query. Noot: ook getest met (i) ASK, en met (ii) andere query patterns waar een comma in zit; alle geteste queries gevalideerd via sparql.org.

```
PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX ex:    <http://www.example.org/example/1.0#>

SELECT ?book ?title
WHERE { 
    ?book dc:title ?title ,
                    ?subtitle;
          dc:author ?author ,
                    ex:Polleke .
}
```

Al tijdens de `dump()` van de query is het ontbreken van de node zichtbaar. Toch is het niet zo dat het type [COMMA] onbekend is, want een `searchElements(element_type=SP.COMMA)` genereert geen foutmelding. Het geeft trouwens een lege resultaatlijst terug. De nodes die de objecten weergeven, `?title`, `?subtitle`, `?author`, en `ex:Polleke`,  zijn allen wel geparsed en beschikbaar. 

Wanneer gezocht wordt op de value van de node, i.e., `searchElements(value=",")`, dan worden de twee laatste nodes van de query geretourneerd. Het lijkt erop alsof een stop-conditie van een loop niet vuurt.
### Source code die het probleem reproduceert

```

from parsertools.parsers import sparqlparser 
from parsertools.parsers.sparqlparser import SPARQLParser as SP

q = '''
PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX ex:    <http://www.example.org/example/1.0#>

SELECT ?book ?title
WHERE { 
    ?book dc:title ?title , ?subtitle;
          dc:author ?author , ex:Polleke .
}
'''

# The query can be parsed
q_p = sparqlparser.parseQuery(q)
# Already in the dump() the [COMMA] can be seen missing
print (q_p.dump())

# Specifically, all 4 objects can be searched for (one set as [ObjectPath], one set as [Object])
objPaths = q_p.searchElements(element_type=SP.ObjectPath , value=None)
print("objectPaths: ", objPaths.__repr__())
objs = q_p.searchElements(element_type=SP.Object, value=None)
print("objects: ", objs.__repr__())

# [SEMICOL]'s are similarly in function to the [COMMA]'s
# [SEMICOL]'s can be searched for
semicols = q_p.searchElements(element_type=SP.SEMICOL)
print("semicols:", semicols)
print("\n== Semicol dumps ==\n")
for count, sc in enumerate(semicols):
    print("semicol ({}):\n".format(count), sc.dump())
print("== ==\n")

# Peculiarly, [COMMA]'s can be searched for! That is, no error is thrown, indicating that its element_type is existing...
commas = q_p.searchElements(element_type=SP.COMMA)
# ... however, none is found
print("commas:", commas)

# When searched for [COMMA] by its value, i.e., value=",", two nodes *are* found ...
commasByValue = q_p.searchElements(value=",")
# ... , albeit not the correct nodes but the final two nodes, which suggests a missed end condition of a loop.
# A possible cause for the missed end condition is the absence of one the ParseStruct (?) attributes that are part of the test condition,
# i.e., probably the criterion is still valid but the data that is being checked is absent
print("commasByValue:", commasByValue)


```
### Output van code

```
parsertools version 0.2.6, build 2647
[QueryUnit] /PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX ex: <http://www.example.org/example/1.0#> SELECT ?book ?title WHERE { ?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke . }/
|  [Query] /PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX ex: <http://www.example.org/example/1.0#> SELECT ?book ?title WHERE { ?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke . }/
|  |  > prologue:
|  |  [Prologue] /PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX ex: <http://www.example.org/example/1.0#>/
|  |  |  [PrefixDecl] /PREFIX dc: <http://purl.org/dc/elements/1.1/>/
|  |  |  |  [PREFIX] /PREFIX/
|  |  |  |  |  PREFIX
|  |  |  |  > prefix:
|  |  |  |  [PNAME_NS] /dc:/
|  |  |  |  |  dc:
|  |  |  |  > namespace:
|  |  |  |  [IRIREF] /<http://purl.org/dc/elements/1.1/>/
|  |  |  |  |  <http://purl.org/dc/elements/1.1/>
|  |  |  [PrefixDecl] /PREFIX ex: <http://www.example.org/example/1.0#>/
|  |  |  |  [PREFIX] /PREFIX/
|  |  |  |  |  PREFIX
|  |  |  |  > prefix:
|  |  |  |  [PNAME_NS] /ex:/
|  |  |  |  |  ex:
|  |  |  |  > namespace:
|  |  |  |  [IRIREF] /<http://www.example.org/example/1.0#>/
|  |  |  |  |  <http://www.example.org/example/1.0#>
|  |  [SelectQuery] /SELECT ?book ?title WHERE { ?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke . }/
|  |  |  [SelectClause] /SELECT ?book ?title/
|  |  |  |  [SELECT] /SELECT/
|  |  |  |  |  SELECT
|  |  |  |  [Var] /?book/
|  |  |  |  |  [VAR1] /?book/
|  |  |  |  |  |  ?book
|  |  |  |  [Var] /?title/
|  |  |  |  |  [VAR1] /?title/
|  |  |  |  |  |  ?title
|  |  |  > where:
|  |  |  [WhereClause] /WHERE { ?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke . }/
|  |  |  |  [WHERE] /WHERE/
|  |  |  |  |  WHERE
|  |  |  |  [GroupGraphPattern] /{ ?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke . }/
|  |  |  |  |  [LCURL] /{/
|  |  |  |  |  |  {
|  |  |  |  |  > pattern:
|  |  |  |  |  [GroupGraphPatternSub] /?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke ./
|  |  |  |  |  |  [TriplesBlock] /?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke ./
|  |  |  |  |  |  |  > subjpath:
|  |  |  |  |  |  |  [TriplesSameSubjectPath] /?book dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke/
|  |  |  |  |  |  |  |  [VarOrTerm] /?book/
|  |  |  |  |  |  |  |  |  [Var] /?book/
|  |  |  |  |  |  |  |  |  |  [VAR1] /?book/
|  |  |  |  |  |  |  |  |  |  |  ?book
|  |  |  |  |  |  |  |  [PropertyListPathNotEmpty] /dc:title ?title , ?subtitle ; dc:author ?author , ex:Polleke/
|  |  |  |  |  |  |  |  |  [VerbPath] /dc:title/
|  |  |  |  |  |  |  |  |  |  [Path] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  [PathAlternative] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  [PathSequence] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  [PathEltOrInverse] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [PathElt] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PathPrimary] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [iri] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PrefixedName] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PNAME_LN] /dc:title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  dc:title
|  |  |  |  |  |  |  |  |  [ObjectListPath] /?title , ?subtitle/
|  |  |  |  |  |  |  |  |  |  [ObjectPath] /?title/
|  |  |  |  |  |  |  |  |  |  |  [GraphNodePath] /?title/
|  |  |  |  |  |  |  |  |  |  |  |  [VarOrTerm] /?title/
|  |  |  |  |  |  |  |  |  |  |  |  |  [Var] /?title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [VAR1] /?title/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  ?title
|  |  |  |  |  |  |  |  |  |  ,
|  |  |  |  |  |  |  |  |  |  [ObjectPath] /?subtitle/
|  |  |  |  |  |  |  |  |  |  |  [GraphNodePath] /?subtitle/
|  |  |  |  |  |  |  |  |  |  |  |  [VarOrTerm] /?subtitle/
|  |  |  |  |  |  |  |  |  |  |  |  |  [Var] /?subtitle/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [VAR1] /?subtitle/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  ?subtitle
|  |  |  |  |  |  |  |  |  [SEMICOL] /;/
|  |  |  |  |  |  |  |  |  |  ;
|  |  |  |  |  |  |  |  |  [VerbPath] /dc:author/
|  |  |  |  |  |  |  |  |  |  [Path] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  [PathAlternative] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  [PathSequence] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  [PathEltOrInverse] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [PathElt] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PathPrimary] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [iri] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PrefixedName] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PNAME_LN] /dc:author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  dc:author
|  |  |  |  |  |  |  |  |  [ObjectList] /?author , ex:Polleke/
|  |  |  |  |  |  |  |  |  |  [Object] /?author/
|  |  |  |  |  |  |  |  |  |  |  [GraphNode] /?author/
|  |  |  |  |  |  |  |  |  |  |  |  [VarOrTerm] /?author/
|  |  |  |  |  |  |  |  |  |  |  |  |  [Var] /?author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [VAR1] /?author/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  ?author
|  |  |  |  |  |  |  |  |  |  ,
|  |  |  |  |  |  |  |  |  |  [Object] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  [GraphNode] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  |  [VarOrTerm] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  |  |  [GraphTerm] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [iri] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PrefixedName] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PNAME_LN] /ex:Polleke/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  ex:Polleke
|  |  |  |  |  |  |  [PERIOD] /./
|  |  |  |  |  |  |  |  .
|  |  |  |  |  [RCURL] /}/
|  |  |  |  |  |  }
|  |  |  [SolutionModifier] //
|  |  [ValuesClause] //

objectPaths:  [ObjectPath("?title"), ObjectPath("?subtitle")]
objects:  [Object("?author"), Object("ex:Polleke")]
semicols: [SEMICOL(";")]

== Semicol dumps ==

semicol (0):
 [SEMICOL] /;/
|  ;

== ==

commas: []
commasByValue: [SolutionModifier(""), ValuesClause("")]

```

**Comment by Jeroen537** [comment]
Moet jij je hierdoor in bochten gaan wringen? Loop je tegen een probleem aan? Ik denk dat ik ook van de separators in het ObjectListPath enz. wel COMMA's kan maken, maar heeft dat nut?

Toelichting: wat je zegt klopt. De komma komt hier niet expliciet terug als ParseStruct element van type COMMA, maar wordt geparsed als eenvoudige string (','). Hij is er dus wel, en wordt gewoon mee-gerendered zoals je kunt zien in de dump.

Vergelijkbare gevallen vind je in ArgList, PathNegatedPropertySet (met een '|' als separator), PathSequence (met een '/'), PathAlternative ('|'), ObjectList (','), ConstructTriples ('.'), ExpressionList (','), TriplesBlock ('.'), en TriplesTemplate ('.').

In deze gevallen hebben de separators geen semantische betekenis maar worden gebruikt om de elementen van een lijst van elkaar te scheiden. Ik had separators het liefst overal als simpele strings geparsed, maar pyParsing maakt dat niet in alle gevallen gemakkelijk. Vandaar dat er soms wel expliciete COMMA's, SEMICOLON's enz. in de parse tree staan.

Functioneel zou dit niet moeten bijten, en voordeel is dat het zo heel eenvoudig is alle elementen in een dergelijke list identiek te labelen in de grammar (zie label "subjpath" voor het herhaalde element TriplesSameSubjectPath in een TriplesBlock).

**Comment by Jeroen537** [comment]
Moet jij je hierdoor in bochten gaan wringen? Loop je tegen een probleem aan? Ik denk dat ik ook van de separators in het ObjectListPath enz. wel COMMA's kan maken, maar heeft dat nut?

Toelichting: wat je zegt klopt op zichzelf. De komma komt hier niet expliciet terug als ParseStruct element van type COMMA, maar wordt geparsed als eenvoudige string (','). Hij is er dus wel, en wordt gewoon mee-gerendered zoals je kunt zien in de dump.

Vergelijkbare gevallen vind je in ArgList, PathNegatedPropertySet (met een '|' als separator), PathSequence (met een '/'), PathAlternative ('|'), ObjectList (','), ConstructTriples ('.'), ExpressionList (','), TriplesBlock ('.'), en TriplesTemplate ('.').

In deze gevallen hebben de separators nauwelijks semantische betekenis maar worden alleen gebruikt om identieke elementen in een lijst lexicaal van elkaar te scheiden. In andere gevallen hebben ze meer betekenis en parse ik ze als expliciete COMMA's, SEMICOLON's enz.

Functioneel zou dit niet moeten bijten, en voordeel is dat het zo heel eenvoudig is alle elementen in een dergelijke list identiek te labelen in de grammar (zie label "subjpath" voor het herhaalde element TriplesSameSubjectPath in een TriplesBlock).

Close?

**Comment by plbt5** [comment]
Ik zou hier wel omheen kunnen, maar omdat 

1. de COMMA en SEMICOLON bijna dezelfde functie hebben, en
2. ik ze beide moet onderscheiden (want ik wil geen gebruik maken van kortschrift in mijn interne structuur), en 
3. ik ze beide dus wil expanderen tot complete (s,p,o) triples;

zou het eenvoudiger zijn als ik ze op dezelfde wijze zou kunnen addresseren.

Maar, nu ik dit zo schrijf, en dus iets boven de details van de code uitstijg: Het achterliggende probleem is dus het kortschrift zelf; twee syntactische wijzes van hetzelfde beschrijven. Een extra methode die het kortschrift expandeerd, zou eigenlijk nog beter zijn, want dan hoef ik er geen rekening meer mee te houden (alhoewel ik de code nu al geschreven heb :-) )

Dus, in die zin zou ik de expansie welkomer vinden dan de [COMMA], op dit moment. Ik weet natuurlijk niet in hoeverre ik de door jou genoemde vergelijkbare gevallen nodig zal gaan hebben. Maar ik zou zeggen: dat is dan van later zorg. Het aspect van de consequentie blijft, uiteraard.

**Comment by Jeroen537** [comment]
Het kortschrift wil ik niet expanderen, want dan ga ik voorbij aan de SPARQL specificatie. De "expansie" zit daar in de semantiek, niet in de syntax en parsertools is een syntax tool. Natuurlijk kun je zelf een functie schrijven die het voor je doet.

Maar waarvoor heb je de COMMA en de SEMICOLON nodig? Dat zijn maar token separators voor de lexicale analyse. De geparsede expressie levert je al precies de elemeten die je nodig hebt, in jouw voorbeeld: de ObjectPath children van het ObjectListPath element. Waar wil je de COMMA's nog voor gebruiken? Ben je zelf een stuk parsing opnieuw aan het implementeren?

**Comment by plbt5** [comment]
Ik heb de COMMA en SEMICOLON niet nodig, en de discussie met jou maakt mijn code weer eenvoudiger, en de absentie van de [COMMA] irrelevanter. De inconsistentie tussen {SEMICOL] en de anderen blijft, maar daar heb ik geen last van. Als volgt:

De annotatie omtrent het type van de graafknopen is erg nuttig voor het semantisch uitrafelen van de query struktuur, die gebaseerd is op die types.

De struktuur van de PropertyListpathNotEmpty in `rdf:type ontoA:Patient ; ontoA:hasTemp ?v , ?t` is `[VerbPath]-[ObjectListPath]-[SEMICOL]-[VerbPath]-[ObjectList]+[Object]-,-[Object]`, of in de dump:
```
[VerbPath] /rdf:type/
[ObjectListPath] /ontoA:Patient/
[SEMICOL] /;/
[VerbPath] /ontoA:hasTemp/
[ObjectList] /?v , ?t/
|  [Object] /?v/
|  ,
|  [Object] /?t/
```
Het algoritme om dit te ontrafelen baseer je op de annotatie, het type knoop. Behalve voor de komma, die daarmee een uitzondering vormt die in de code moet worden ondervangen. 

Om deze inconsistentie te omzeilen baseer ik me nu nog sterker op de struktuur, nl de observatie dat een PLPNE altijd uit tweetallen [Verb, Object] bestaat (dus negeer het tussenliggende element), en een ObjectList altijd uit één [object] bestaat (negeer het tussenliggende element). Daarmee ontstaat een duidelijker algoritme en wellicht robuustere code dan de elementen sec 1-voor-1 beschouwen. 

Dus vervalt voor mij de noodzaak voor dit issue/feature request. Ik stel voor de inconsistentie pas aan te pakken als zich dat daadwerkelijk presenteert.

Weer bedankt,
     Paul
p.s. Introspectie: Hier was duidelijk sprake van code smell van mijn kant. Wat ik dus niet geroken heb, maar waarvan ik deze specifieke geur nu ken, zodat ik er van uit ga dat ik deze in het vervolg zal herkennen.

**Comment by Jeroen537** [comment]
Ik begrijp niet alles, maar ik hoef dat ook niet. Jouw taak om er iets van te maken.

Alleen één opmerking: Wat betreft de PLPNE, als je robuuste code wilt schrijven - en dat moet je willen - dan moet je met alle variaties rekening houden en niet alleen met die in jouw query voorkomt. De grammar is je uitgangspunt. Grondregel.

**Comment by plbt5** [comment]
Grammar moet zeker het uitgangspunt zijn, en is dat ook. Sectie 19.8 uit de SPARQL REC staat dan ook open als ik aan de code werk. Maar alleen voor wat betreft de grammar die ik nu nodig heb, niet op voorhand alles, want anders komt dit nooit tot een goed einde.

**Comment by Jeroen537** [comment]
Snap hoe je denkt, maar heb hier grote twijfels bij. Hier ga je mee vastlopen.

Als je in je code er van uitgaat dat bijv. "een PLPNE altijd uit tweetallen [Verb, Object] bestaat”, dan schrijf je code die maar in bepaalde gevallen werkt en in andere gevallen een ongedefinieerd resultaat geeft. Om zulke code met je laten meegroeien is vrijwel ondoenlijk.

Zorg daarom dat je code in ieder geval bestand is tegen elke willekeurige legale invoer, en altijd een welgedefinieerd antwoord geeft, als is het maar “conditie zus en zo is nog niet geimplementeerd”, dus compleet met analyse wat er aan de hand is waarom het nog niet werkt. Deze acties ook in je unittests meenemen.

Jammer, maar dit kun je niet versnellen. Je zult geduldig moeten doen wat er gedaan moet worden.

Jeroen.

**Comment by plbt5** [comment]
Uiteraard zorg ik ervoor dat ik overige mogelijkheden als een Else-clause, of de gewenste mogelijheid als een assert-clause implementeer. Alles wat dan buiten mijn verwachting valt, wordt daarmee geflagged.

Daarin kun je wel helpen. Ik begon een grouping-functie op the ParseStruct te schrijven, maar zou het eigenlijk geen nuttige toevoeging op het parserplatform zijn. Dus, gegeven een branching node, itereer over de _groepen_ branches die de huidige node gezamenlijk hebben. Die splitsing is lexicografisch, toch, gebaseerd op het voor die node specifieke scheidingsteken. Ik kan me althans geen situatie voorstellen waarbij een branching node de scheiding in groepen _niet_ baseert op een lexicografische regel.

Hoe zie jij dit?

Paul

**Comment by Jeroen537** [comment]
Uit je beschrijving begrijp ik niet waar je om vraagt.

Wel in het algemeen het volgende: dit klinkt als iets wat je via de API kunt realiseren. Dan heb ik daar geen rol te spelen.

Jeroen.

**Comment by plbt5** [comment]
Ja, dit kan via de API worden gerealiseerd. Dus dat zal ik doen, tenzij je het zelf een nuttige aanvulling vindt op het sparql framework. Ik bedoel het volgende:

1. In EBNF kan een repetition worden gedefinieerd, bijv.: `<args> ::= <arg1> <arg2> ( "+" <args>) *`.
Hierin noem ik `"+"` een separator. 
1. Dit uit zich in de graph als een `<args>`-node die groepen van 2 subnodes kent (`<arg1>`-node,  `<arg2>`-node), gescheiden door een groepsseparator node, `"+"`-node. De  `<args>`-node is daarmee een branching node geworden.
1. Mijn semantische parsing, maar ik neem aan ook andermans semantische parsers, is geïnteresseerd in de groepen (`<arg1>`-node,  `<arg2>`-node) en niet zozeer in de scheidingsnode. Vandaar de suggestie voor een `getSiblings()`-methode die van een branching node een lijst van groepen van siblings teruggeeft, hier dus [(`<arg1>`-node,  `<arg2>`-node), (`<arg1>`-node,  `<arg2>`-node), ...].

Wellicht is dit een té specifieke methode om op te nemen in het framework? Anderszijds kan ik me voorstellen dat het juist nuttig is als uitbreiding op de bestaande API omdat de _taaldefinitie_ de kennis al expliciet maakt op welk scheidingsteken de groepsherhaling is gebaseerd. Dan is de kernvraag: Wat is het criterium waarop gebaseerd wordt of iets wel of niet in een API wordt opgenomen? Is dat minimale duplicatie, dus als het op basis van de API gemaakt kan worden, dan niet opnemen in de API; of is dat transparantie cq separation of concerns, dus als de kennis toegevoegd moet worden aan de kennis van de API-gebruiker, dan wel opnemen in de API? Ondanks dat minimale duplicatie een goed ontwerpprincipe is, neig ik naar de tweede omdat zich dat uit in loose coupling. Ik noem het transparantie, niet omdat de semantische parser geen weet _mag_ hebben van hoe de scheiding is geïmplementeerd, maar omdat het er geen weet van _hoeft_ te hebben, want tenslotte is de wijze waarop de scheiding wordt gerealiseerd een lexicografische kwestie en niet een semantische. En volgens Separation of Concerns hoort de methode dan bij de lexicografische parser te liggen.

Afgezien of je besluit om dit wel of niet op te nemen in de API, dat in ultimo natuurlijk jouw beslissing is, ben ik nieuwsgieriger naar jouw architecturele blik hierop.

Paul

**Comment by Jeroen537** [comment]
Zou moeten zijn opgelost vanaf build 2758, in branch "NoStringDelimiters".

**Comment by Jeroen537** [comment]
Build 2888

**Comment by Jeroen537** [comment]
Build 3003
