### ISSUE TITLE
WTH

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#2]
PREFIX ns: 	<http://ds.tno.nl>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>

SELECT ?p ?t WHERE 
	{
		?p a foaf:Person .
		?p ns:hasTemp ?t .
         ?t a ns:TempInC .
         FILTER ( (datatype(?t) = xsd:float) &&
         			( ?t > 37.0 ) 
         		).
    }

**Comment by Jeroen537** [comment]
Zelfde probleem.

Ik zie dat ik zelf de niet zo behulpzame melding “Query cannot be parsed” geef. Ik zal een iets meer informatieve melding toevoegen.

Jeroen.
