### ISSUE TITLE
Cannot be parsed

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#3]
PREFIX ns:     <http://ds.tno.nl>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>

SELECT ?p ?t WHERE 
    {
        ?p a foaf:Person .
        ?p ns:hasTemp ?t .
        ?p ns:hasAge ?a .
         ?t a ns:TempInC .
         FILTER ( (datatype(?t) = xsd:float) &&
                     ( ?t > 37.0 ) &&
                     ( ?a < 37.0 ) 
                 ).
    }

**Comment by Jeroen537** [comment]
Als ik de query voer aan 
http://www.sparql.org/query.html
krijg ik ook een fout. Namespace moet blijkbaar een IRIref met <> zijn.
Error 400: Parse error: PREFIX ns: http://ds.tno.nl PREFIX foaf: http://xmlns.com/foaf/0.1/ SELECT ?p ?t WHERE { ?p a foaf:Person . ?p ns:hasTemp ?t . ?p ns:hasAge ?a . ?t a ns:TempInC . FILTER ( (datatype(?t) = xsd:float) && ( ?t > 37.0 ) && ( ?a < 37.0 ) ). } Encountered " <PNAME_NS> "http: "" at line 1, column 12. Was expecting: <IRIref> ... Fuseki - version 1.1.2 (Build date: 2015-03-08T09:49:20+0000)

> Op 8 mrt. 2016 om 17:27 heeft Paul Brandt <notifications@github.com> het volgende geschreven:
> 
> PREFIX ns: http://ds.tno.nl
> PREFIX foaf: http://xmlns.com/foaf/0.1/
> 
> SELECT ?p ?t WHERE 
> {
> ?p a foaf:Person .
> ?p ns:hasTemp ?t .
> ?p ns:hasAge ?a .
> ?t a ns:TempInC .
> FILTER ( (datatype(?t) = xsd:float) &&
> ( ?t > 37.0 ) &&
> ( ?a < 37.0 ) 
> ).
> }

**Comment by plbt5** [comment]
Vreemd dat ik jou die query heb gegeven want in mijn testcode staan de <> er wel omheen. Ik zag trouwens dat de query sowieso niet goed was omdat de xsd: prefis definition ontbrak.
Het ziet er nu als volgt uit, maar die komt er ook niet doorheen, terwijl het wel goed gaat op sparql.org.

PREFIX ns:     <http://ds.tno.nl>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema>

SELECT ?p ?t WHERE 
    {
        ?p a foaf:Person .
        ?p ns:hasTemp ?t .
        ?p ns:hasAge ?a .
         ?t a ns:TempInC .
         FILTER ( (datatype(?t) = xsd:float) &&
                     ( ?t > 37.0 ) &&
                     ( ?a < 37.0 ) 
                 ).
    }

**Comment by Jeroen537** [comment]
Hersteld. Er zat een fout in de functie die eventuele comments stript alvorens te parsen.
