### ISSUE TITLE
Inconsequent generation of tag with [Expression] - Low Priority

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#4]
Query:
```sparql
PREFIX ns:     <http://ds.tno.nl>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema>

SELECT ?p ?t WHERE 
    {
        ?p a foaf:Person ;
        ns:hasTemp ?t .
        ?t ns:hasAge ?a .
         FILTER ( ( ?t > ?a ) &&
                           ?a < 37.0 &&
                  langMatches(lang(?p), "EN")
                 ).
    } 
```

This query will be parsed, such that  
* `[Expression] /LANG ( ?p )/` will generate a tag `> language-tag:`,
* `[Expression] /"EN"/` will generate a tag `> language-range:`, 
* `[Expression] /?p/` will generate a tag `> expression:`, and
* `[Expression] /?a < 37.0/` will generate tag `> expression:`.

Although the first two are understood, they suggest a specificity that is contradicted by the second two.

**Comment by Jeroen537** [comment]
Ik begrijp het niet. Ik parse:
PREFIX ns:     <http://ds.tno.nl>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema>

SELECT ?p ?t WHERE 
    {
        ?p a foaf:Person ;
        ns:hasTemp ?t .
        ?t ns:hasAge ?a .
         FILTER ( ( ?t > ?a ) &&
                           ?a < 37.0 &&
                  langMatches(?p, "EN")
                 ).
    } 
en zie (fragment):
|  |  |  |  |  |  |  |  |  |  |  |  |  [ValueLogical] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  [RelationalExpression] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [NumericExpression] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [AdditiveExpression] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [MultiplicativeExpression] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [UnaryExpression] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PrimaryExpression] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [BuiltInCall] /LANGMATCHES ( ?p , "EN" )/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [LANGMATCHES_kw] /LANGMATCHES/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  LANGMATCHES
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  (
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  > language-tag:
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [Expression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [ConditionalOrExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [ConditionalAndExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [ValueLogical] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [RelationalExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [NumericExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [AdditiveExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [MultiplicativeExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [UnaryExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PrimaryExpression] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [Var] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [VAR1] /?p/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  ?p
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  ,
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  > language-range:
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [Expression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [ConditionalOrExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [ConditionalAndExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [ValueLogical] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [RelationalExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [NumericExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [AdditiveExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [MultiplicativeExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [UnaryExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [PrimaryExpression] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [RDFLiteral] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  > lexical_form:
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [String] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  > testString:
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  [STRING_LITERAL2] /"EN"/
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  "EN"
Bij mij zie ik dus nog steeds een language tag bij ?p. Wat heb jij gedaan?

**Comment by plbt5** [comment]
Ach natuurlijk.
De Tag idientificeert de terminator en niet de eerste node in de tree daar naartoe: ik zag direct boven [expression] een adere tag staan, maar dat klopt want het verschil zit dieper in de tree en niet in de eerste node.
Suf


________________________________
Van: Jeroen537 [notifications@github.com]
Verzonden: zaterdag 19 maart 2016 11:25
Aan: Jeroen537/parser
CC: Brandt, P.
Onderwerp: Re: [parser] Inconsequent generation of tag with [Expression] - Low Priority (#4)


Ik begrijp het niet. Ik parse:
PREFIX ns: http://ds.tno.nl
PREFIX foaf: http://xmlns.com/foaf/0.1/
PREFIX xsd: http://www.w3.org/2001/XMLSchema

SELECT ?p ?t WHERE
{
?p a foaf:Person ;
ns:hasTemp ?t .
?t ns:hasAge ?a .
FILTER ( ( ?t > ?a ) &&
?a < 37.0 &&
langMatches(?p, "EN")
).
}
en zie (fragment):
| | | | | | | | | | | | | [ValueLogical] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | [RelationalExpression] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | [NumericExpression] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | | [AdditiveExpression] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | | | [MultiplicativeExpression] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | | | | [UnaryExpression] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | | | | | [PrimaryExpression] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | | | | | | [BuiltInCall] /LANGMATCHES ( ?p , "EN" )/
| | | | | | | | | | | | | | | | | | | | | [LANGMATCHES_kw] /LANGMATCHES/
| | | | | | | | | | | | | | | | | | | | | | LANGMATCHES
| | | | | | | | | | | | | | | | | | | | | (
| | | | | | | | | | | | | | | | | | | | | > language-tag:
| | | | | | | | | | | | | | | | | | | | | [Expression] /?p/
| | | | | | | | | | | | | | | | | | | | | | [ConditionalOrExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | [ConditionalAndExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | [ValueLogical] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | [RelationalExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | [NumericExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | [AdditiveExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | [MultiplicativeExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | [UnaryExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [PrimaryExpression] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [Var] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [VAR1] /?p/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ?p
| | | | | | | | | | | | | | | | | | | | | ,
| | | | | | | | | | | | | | | | | | | | | > language-range:
| | | | | | | | | | | | | | | | | | | | | [Expression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | [ConditionalOrExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | [ConditionalAndExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | [ValueLogical] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | [RelationalExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | [NumericExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | [AdditiveExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | [MultiplicativeExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | [UnaryExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [PrimaryExpression] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [RDFLiteral] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | > lexical_form:
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [String] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | > testString:
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | [STRING_LITERAL2] /"EN"/
| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | "EN"
Bij mij zie ik dus nog steeds een language tag bij ?p. Wat heb jij gedaan?

**Comment by plbt5** [comment]
Bij deze sluit ik het issue dan ook weer.
