### ISSUE TITLE
FeatureReq: getParent(), getChildren()

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#6]
If I search for an element with `.SearchElements(pattern)`, then the result is ParseInfo node. Very convenient, however the context of its position in the tree has been lost.

It would be very convenient if I could determine its position by either going deeper into the tree (`getChildren()`) or going shallower to the root (`getParent()`). 

**getChildren()**: returns at least the child at one level deeper in the tree, and, if present, any possible siblings of that child, or None if the current element is the terminator already.

**getParent()**: returns the first ancestor node that has siblings.  
Effectively, getParents() makes the path that consists of nodes between the current node and the first branching node, transparent.

**Comment by Jeroen537** [comment]
Implemented getChildren as requested (always returns a list, possibly with 0 or 1 element, and getParent(start) with a start parameter to provide a context for the search.
Implementation note: currently there are no backpointers to the parent, therefore a starting point for the search must be provided. This may or may not change in a later revision.
