### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#9]
Have labels in the tree in order to directly address a node:
* Prefix Declarations:
  * BASE
  * PREFIX
* Query Pattern:
  * WHERE
  * Constraint

**Comment by Jeroen537** [comment]
Gedaan. 

Ik heb ook labels voor Update en voor Prologue toegevoegd, dan kun je er vanaf de top van de query bij. 

Bijv:

s = 'BASE <work:22?> SELECT REDUCED $var1 ?var2 (("*Expression*") AS $var3) { SELECT * {} } GROUP BY ROUND ( "*Expression*") VALUES $S { <testIri> <testIri> }'
parseQuery(s)
 
s = 'BASE <prologue:22> PREFIX prologue: <prologue:33> LOAD <testIri> ; BASE <prologue:22> PREFIX prologue: <prologue:33>'
r = parseQuery(s)
  
print(r.dump())

print(r)
print()
print(r.update)
print()
print(r.update.prologue)
print()
r.update.prologue.base.updateWith('BASE <niets:niks>')
print(r.update.prologue.dump())


Constraints zit wat dieper, het handigst is denk ik eerst te zoeken op FILTER en dan .dot access te doen.

Jeroen.

PS Geen release van gemaakt, maar staat wel op de server.
